### ISSUE TITLE
 Can't run without gradethis package

### ISSUE THREAD

**Issue by elizabethmitchell** [asteves/cinfeRence#2]
I can't run a tutorial without installing the gradethis package, but when I attempt to install the gradethis package, I get the following message, and the package does not install:
Warning in install.packages :
  package ‘gradethis’ is not available for this version of R

Session info:
 setting  value                       
 version  R version 4.0.5 (2021-03-31)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Los_Angeles         
 date     2021-05-20                  

- Packages ---------------------------------------------------------
 package     * version date       lib
 bslib         0.2.5.1 2021-05-18 [1]
 cinfeRence  * 0.0.1   2021-05-20 [1]
 cli           2.5.0   2021-04-26 [1]
 digest        0.6.27  2020-10-24 [1]
 ellipsis      0.3.2   2021-04-29 [1]
 evaluate      0.14    2019-05-28 [1]
 fastmap       1.1.0   2021-01-25 [1]
 htmltools     0.5.1.1 2021-01-22 [1]
 htmlwidgets   1.5.3   2020-12-10 [1]
 httpuv        1.6.1   2021-05-07 [1]
 jquerylib     0.1.4   2021-04-26 [1]
 jsonlite      1.7.2   2020-12-09 [1]
 knitr         1.33    2021-04-24 [1]
 later         1.2.0   2021-04-23 [1]
 learnr      * 0.10.1  2020-02-13 [1]
 lifecycle     1.0.0   2021-02-15 [1]
 magrittr      2.0.1   2020-11-17 [1]
 markdown      1.1     2019-08-07 [1]
 mime          0.10    2021-02-13 [1]
 promises      1.2.0.1 2021-02-11 [1]
 R6            2.5.0   2020-10-28 [1]
 Rcpp          1.0.6   2021-01-15 [1]
 renv          0.13.2  2021-03-30 [1]
 rlang         0.4.11  2021-04-30 [1]
 rmarkdown     2.8     2021-05-07 [1]
 rprojroot     2.0.2   2020-11-15 [1]
 sass          0.4.0   2021-05-12 [1]
 sessioninfo   1.1.1   2018-11-05 [1]
 shiny       * 1.6.0   2021-01-25 [1]
 stringi       1.5.3   2020-09-09 [1]
 stringr       1.4.0   2019-02-10 [1]
 withr         2.4.2   2021-04-18 [1]
 xfun          0.22    2021-03-11 [1]
 xtable        1.8-4   2019-04-21 [1]
 yaml          2.2.1   2020-02-01 [1]
 source                             
 CRAN (R 4.0.5)                     
 Github (asteves/cinfeRence@661b591)
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.4)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.3)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     
 CRAN (R 4.0.5)                     

[1] C:/Users/mitch/OneDrive/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.5/library

**Comment by asteves** [comment]
Looks like the issue is that gradethis and learnr have to be installed from development version. Have updated README accordingly.
